In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [ ]:
import numpy as np
marks = np.array([80,85,90,95])
marks += 5
print(marks)

In [10]:
import numpy as np
m = np.array([
    [80, 90, 70],
    [85, 95, 75],
    [70, 80, 90]
])
print(m)




[[80 90 70]
 [85 95 75]
 [70 80 90]]
2
(3, 3)
9
int64


In [ ]:
print(m.ndim)

In [ ]:
print(m.shape)#size of each dimention

In [11]:
print(m.size)

9


In [ ]:
print(m.dtype)

In [12]:
print(m[0][0])
print(m[0][1])
print(m[0][2])
print(m[1][0])
print(m[1][1])
print(m[1][2])
print(m[2][0])
print(m[2][1])
print(m[2][2])

80
90
70
85
95
75
70
80
90


**2D Slicing**

In [14]:
import numpy as np
m = np.array([
    [80, 90, 70],
    [85, 95, 75],
    [70, 80, 90]
])
print(m[0:2,1:3])
#[0:2] -> row 0 and 1
#[1:3] -> columns 1 and 2

[[90 70]
 [95 75]]


**np.zeros()**

In [15]:
import numpy as np
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [17]:
import numpy as np
a = np.zeros((5,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**np.ones()**

In [22]:
import numpy as np
a = np.ones((5,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**np.arange() - similar to range in for loop**

In [23]:
import numpy as np
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


# Array Operations

**Arithmetic**

In [24]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[0 0 0]
[10 10 10]


**2)Comparision**

In [28]:
#Boolean Values
a = np.array([10,20,30])
print(a>20)

[False False  True]


In [29]:
#Values
a = np.array([10,20,30])
print(a[a>20])

[30]


In [30]:
print(a==20)

[False  True False]


In [31]:
print(a[a != 20])

[10 30]


In [32]:
print(a[a>=20])

[20 30]


# Mathematical Functions

In [37]:
m = np.array([75,80,85,90,95])
print(np.sum(m))
print(np.max(m))
print(np.min(m))
print(np.mean(m))#Average

425
95
75
85.0


In [40]:
m = np.array([
    [80, 90, 70],
    [85, 95, 75],
    [70, 80, 90]
])

#Colum - wise sum
print("Column wise: ",np.sum(m, axis=0))

#Row - wise sum
print("Row wise: ",np.sum(m, axis=1))

Column wise:  [235 265 235]
Row wise:  [240 255 240]


**Reshape**

In [44]:
a = np.array([10,20,30,40,50,60])
b = a.reshape(2,3)#Product of these two = len of array. Then only execute
print(b)

[[10 20 30]
 [40 50 60]]
